sudo: required
services:
  - docker

before_install:
  - docker build -t lkececi/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true lkececi/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-west-1"
  app: "docker-react2"
  env: "Dockerreact2-env"
  bucket_name: "elasticbeanstalk-eu-west-1-854597615242"
  bucket_path: "docker-react2"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"